[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "momo"
version = "0.1.0"
authors = [
  { name="Łukasz Bondaruk", email="lukas.bond07@gmail.com" },
  { name="Oskar Bartosz", email="oskbsz@gmail.com" },
  { name="Andrzej Kusiak", email="andrzej.kusiak00@gmail.com" }]
description = "Hub for music machine learning  generating audio"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "coloredlogs>=15.0.1",
  "pycodestyle==2.10.0",
  "pylint==2.16.2",
  "mypy==1.5.0",
  "numpy==1.23.5"]

[project.urls]
"Homepage" = "https://github.com/Szakulli07/coopertunes"

[tool.setuptools.package-dir]
coopertunes = "coopertunes"

[pycodestyle]
max-line-length = 100

[tool.pylint.MAIN]
fail-under = 10

[tool.pylint.DESIGN]
max-args = 12

[tool.pylint.'MESSAGES CONTROL']
disable = [
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring",
  "duplicate-code",
  "too-many-locals",
  "too-many-branches",
  "too-many-instance-attributes",
  "too-many-statements",
  "too-few-public-methods",
  "consider-using-from-import",
  "invalid-name"]

[tool.pylint.TYPECHECK]
generated-members = "torch.*"
