name: 'Check PR Branch'

on:
  pull_request:
    branches: [ main ]

jobs:
  check_branch:
    runs-on: [ code-linux, code-default ]
    steps:
      - name: Check branch
        if: github.base_ref == 'main' && github.head_ref != 'develop'
        run: |
          echo "ERROR: You can only merge to main from develop."
          exit 1
